# Generated by Django 5.0.3 on 2024-04-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscription_options_subscription_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="pago"),
        ),
    ]
