# Generated by Django 5.0.3 on 2024-06-06 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_speaker_options_alter_speaker_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("E", "Email"), ("P", "Phone")], max_length=1
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.speaker"
                    ),
                ),
            ],
        ),
    ]
