# Generated by Django 5.0.3 on 2024-10-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('core', '0007_alter_talk_title_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
        migrations.AlterModelOptions(
            name='courseold',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
