# Generated by Django 5.0.3 on 2024-10-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_course_abc_to_mti"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseOld",
        ),
    ]
