name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev
          cp contrib/env-sample .env

      - name: Run flake8
        run: |
          pipenv run flake8 .

      - name: Run tests
        run: |
          pipenv run python manage.py test
